# Generated by Django 5.1.5 on 2025-09-20 18:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(db_index=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='contact',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contact',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], db_index=True, default='medium', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('read', 'Read'), ('replied', 'Replied'), ('closed', 'Closed')], db_index=True, default='new', max_length=20),
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='contactcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='contactcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='contact_type',
            field=models.CharField(choices=[('office', 'Office'), ('emergency', 'Emergency'), ('media', 'Media'), ('general', 'General')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='contactinfo',
            name='title',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('international', 'International'), ('domestic', 'Domestic'), ('training', 'Training'), ('tournament', 'Tournament'), ('friendly', 'Friendly')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], db_index=True, default='upcoming', max_length=20),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='eventcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='generalranking',
            name='category',
            field=models.CharField(choices=[('team', 'Team'), ('player', 'Player'), ('batting', 'Batting'), ('bowling', 'Bowling'), ('all-rounder', 'All-rounder')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='generalranking',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='generalranking',
            name='rank',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='generalranking',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='category',
            field=models.CharField(choices=[('matches', 'Matches'), ('events', 'Events'), ('training', 'Training'), ('awards', 'Awards'), ('behind_scenes', 'Behind the Scenes'), ('interviews', 'Interviews')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='media',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='media_type',
            field=models.CharField(choices=[('photo', 'Photo'), ('video', 'Video'), ('gallery', 'Gallery'), ('document', 'Document')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='media',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='media',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='news',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='news',
            name='published_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='news',
            name='views',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='newscategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='age',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_captain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_featured',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='is_vice_captain',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='player',
            name='jersey_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='join_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='matches_played',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='player',
            name='role',
            field=models.CharField(choices=[('batsman', 'Batsman'), ('bowler', 'Bowler'), ('all-rounder', 'All-rounder'), ('wicket-keeper', 'Wicket-keeper')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='runs_scored',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='player',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('injured', 'Injured'), ('retired', 'Retired'), ('suspended', 'Suspended')], db_index=True, default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='player',
            name='wickets_taken',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='category',
            field=models.CharField(choices=[('batting', 'Batting'), ('bowling', 'Bowling'), ('all-rounder', 'All-rounder')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='country',
            field=models.CharField(db_index=True, default='Afghanistan', max_length=100),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='format',
            field=models.CharField(choices=[('t20i', 'T20I'), ('odi', 'ODI'), ('test', 'Test')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='player_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='playerranking',
            name='rank',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='rankingcategory',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='rankingcategory',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='join_date',
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='member_type',
            field=models.CharField(choices=[('management', 'Management'), ('coaches', 'Coaches'), ('staff', 'Staff'), ('players', 'Players')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='teammember',
            name='position',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='country_code',
            field=models.CharField(db_index=True, default='AFG', max_length=3),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='format',
            field=models.CharField(choices=[('t20i', 'T20I'), ('odi', 'ODI'), ('test', 'Test')], db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='is_published',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='rank',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='teamranking',
            name='team_name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='teamrole',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='teamrole',
            name='name',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='capacity',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='country',
            field=models.CharField(db_index=True, default='Afghanistan', max_length=100),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(db_index=True, max_length=200),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['-created_at'], name='api_contact_created_b984ff_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['status', 'priority'], name='api_contact_status_90ad82_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['category', 'status'], name='api_contact_categor_d7dc17_idx'),
        ),
        migrations.AddIndex(
            model_name='contact',
            index=models.Index(fields=['email', 'status'], name='api_contact_email_391e68_idx'),
        ),
        migrations.AddIndex(
            model_name='contactcategory',
            index=models.Index(fields=['name', 'is_active'], name='api_contact_name_0a8a78_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinfo',
            index=models.Index(fields=['order', 'contact_type'], name='api_contact_order_743166_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinfo',
            index=models.Index(fields=['is_active', 'contact_type'], name='api_contact_is_acti_ddd678_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['-date'], name='api_event_date_9ec950_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['status', 'date'], name='api_event_status_2fefd8_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_featured', 'is_published'], name='api_event_is_feat_92103e_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_type', 'status'], name='api_event_event_t_f1d2ba_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category', 'status'], name='api_event_categor_085c59_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['venue', 'date'], name='api_event_venue_i_8e24a0_idx'),
        ),
        migrations.AddIndex(
            model_name='eventcategory',
            index=models.Index(fields=['name', 'is_active'], name='api_eventca_name_f3678e_idx'),
        ),
        migrations.AddIndex(
            model_name='generalranking',
            index=models.Index(fields=['category', 'rank'], name='api_general_categor_81f4de_idx'),
        ),
        migrations.AddIndex(
            model_name='generalranking',
            index=models.Index(fields=['is_published', 'category'], name='api_general_is_publ_3613b8_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-created_at'], name='api_media_created_14453c_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['media_type', 'is_published'], name='api_media_media_t_9b7a0b_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['category', 'is_published'], name='api_media_categor_a1308b_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['is_featured', 'is_published'], name='api_media_is_feat_bb7575_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-views'], name='api_media_views_26edda_idx'),
        ),
        migrations.AddIndex(
            model_name='media',
            index=models.Index(fields=['-published_at'], name='api_media_publish_0755da_idx'),
        ),
        migrations.AddIndex(
            model_name='mediacategory',
            index=models.Index(fields=['name', 'is_active'], name='api_mediaca_name_bb1ae2_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-created_at'], name='api_news_created_4b7959_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['status', '-published_at'], name='api_news_status_6ecf1d_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_featured', 'status'], name='api_news_is_feat_a632fa_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['category', 'status'], name='api_news_categor_3f8e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['author', 'status'], name='api_news_author__6319e0_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['-views'], name='api_news_views_d1ef71_idx'),
        ),
        migrations.AddIndex(
            model_name='newscategory',
            index=models.Index(fields=['name', 'is_active'], name='api_newscat_name_c30b14_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['jersey_number', 'name'], name='api_player_jersey__f50120_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['role', 'status'], name='api_player_role_e55c20_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_featured', 'status'], name='api_player_is_feat_24913c_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['is_captain', 'is_vice_captain'], name='api_player_is_capt_fe64e1_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-matches_played'], name='api_player_matches_11bb39_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-runs_scored'], name='api_player_runs_sc_0c0d92_idx'),
        ),
        migrations.AddIndex(
            model_name='player',
            index=models.Index(fields=['-wickets_taken'], name='api_player_wickets_20a786_idx'),
        ),
        migrations.AddIndex(
            model_name='playerranking',
            index=models.Index(fields=['category', 'format', 'rank'], name='api_playerr_categor_36d934_idx'),
        ),
        migrations.AddIndex(
            model_name='playerranking',
            index=models.Index(fields=['is_published', 'category', 'format'], name='api_playerr_is_publ_2dc4b8_idx'),
        ),
        migrations.AddIndex(
            model_name='playerranking',
            index=models.Index(fields=['player', 'category'], name='api_playerr_player__0b4cb0_idx'),
        ),
        migrations.AddIndex(
            model_name='playerranking',
            index=models.Index(fields=['country', 'category'], name='api_playerr_country_baa5f4_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingcategory',
            index=models.Index(fields=['name', 'is_active'], name='api_ranking_name_973450_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['member_type', 'order', 'name'], name='api_teammem_member__9f81a6_idx'),
        ),
        migrations.AddIndex(
            model_name='teammember',
            index=models.Index(fields=['is_active', 'member_type'], name='api_teammem_is_acti_453f79_idx'),
        ),
        migrations.AddIndex(
            model_name='teamranking',
            index=models.Index(fields=['format', 'rank'], name='api_teamran_format_648746_idx'),
        ),
        migrations.AddIndex(
            model_name='teamranking',
            index=models.Index(fields=['is_published', 'format'], name='api_teamran_is_publ_016bfa_idx'),
        ),
        migrations.AddIndex(
            model_name='teamranking',
            index=models.Index(fields=['country_code', 'format'], name='api_teamran_country_b41c84_idx'),
        ),
        migrations.AddIndex(
            model_name='teamrole',
            index=models.Index(fields=['name', 'is_active'], name='api_teamrol_name_5d2ac0_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name'], name='api_venue_name_7913fc_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['city', 'country'], name='api_venue_city_c6a1eb_idx'),
        ),
    ]
