# Generated by Django 5.1.5 on 2025-11-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AboutTeam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(db_index=True, max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("position", models.CharField(db_index=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="about_team/"),
                ),
                ("bio", models.TextField(blank=True, null=True)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("order", models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                "ordering": ["order", "name"],
                "indexes": [
                    models.Index(
                        fields=["order", "name"], name="api_aboutte_order_6f1e2c_idx"
                    ),
                    models.Index(
                        fields=["is_active"], name="api_aboutte_is_acti_9ca704_idx"
                    ),
                ],
            },
        ),
    ]
