# Generated by Django 5.1.5 on 2025-09-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_optimize_performance"),
    ]

    operations = [
        migrations.CreateModel(
            name="PageView",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "page",
                    models.CharField(
                        choices=[
                            ("home", "Home"),
                            ("news", "News"),
                            ("media", "Media"),
                            ("rankings", "Rankings"),
                            ("team", "Team"),
                            ("events", "Events"),
                            ("about", "About"),
                            ("contact", "Contact"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "section",
                    models.CharField(
                        choices=[
                            ("hero", "Hero Section"),
                            ("rankings", "Rankings Section"),
                            ("news", "News Section"),
                            ("media", "Media Section"),
                            ("events", "Events Section"),
                            ("team", "Team Section"),
                            ("stats", "Statistics Section"),
                            ("full_page", "Full Page"),
                        ],
                        db_index=True,
                        default="full_page",
                        max_length=20,
                    ),
                ),
                ("views", models.PositiveIntegerField(db_index=True, default=0)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-views"],
                "indexes": [
                    models.Index(
                        fields=["page", "section"], name="api_pagevie_page_bafdb5_idx"
                    ),
                    models.Index(
                        fields=["-views"], name="api_pagevie_views_cb8fb5_idx"
                    ),
                ],
                "unique_together": {("page", "section")},
            },
        ),
    ]
