# Generated by Django 5.1.5 on 2025-09-22 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_pageview"),
    ]

    operations = [
        migrations.DeleteModel(
            name="PageView",
        ),
    ]
